spring:
  application:
    name: coin-notify
  config:
    import: optional:file:.env[.properties]
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
logging:
  level:
    org.springframework.r2dbc.core: DEBUG
    io.r2dbc: DEBUG